### ISSUE TITLE
Crash on Waterfox loading saved page with large gifs

### ISSUE THREAD

**Issue by robbely** [gildas-lormeau/SingleFileZ#172]
If I use SingleFilesZ to save the page from "https://store.steampowered.com/app/1722660/Hamster_on_Rails/" as an example with large gifs, the file appears to save correctly. However if I reload into Waterfox (latest: G6.0.5 based on latest Firefox ESR) I get the Gah Tab Crashed error.  (The saved page loads successfully however in the equivalent Firefox ESR release).

I've tried with clean install of Waterfox and not changing any SingleFileZ settings.

If I open the saved page in winrar and delete the 3 large gifs from the images folder the page will then load successfully in Waterfox.

**Comment by gildas-lormeau** [comment]
I must confess that I don't know how I can help you. The file is decompressed before being displayed. As a result, memory consumption is impacted during this stage.

I suppose that with SingleFile, this might not be a problem. FYI, I have merged SingleFileZ into SingleFile. The "File format" section in the options page lets you choose the output format.

**Comment by robbely** [comment]
> I must confess that I don't know how I can help you. The file is decompressed before being displayed. As a result, memory consumption is impacted during this stage.

Memory consumption was my thought too, it's odd that it only happens in the one variant of firefox (I've tried on tor browser too - again the same esr version and that one loads the saved page ok too).

Do you know if there are any about:config settings that might allow more memory in a tab before the tab gives up and crashes?

**Comment by gildas-lormeau** [comment]
I added quite recently a new feature that allows SFZ pages to be opened in any browser without having to install the extension (like SF). It's enabled by default. Maybe disabling it could fix this issue, cf. `ZIP content > add metadata to extract data from the page` option.

**Comment by robbely** [comment]
> I added quite recently a new feature that allows SFZ pages to be opened in any browser without having to install the extension (like SF). It's enabled by default. Maybe disabling it could fix this issue, cf. `ZIP content > add metadata to extract data from the page` option.

Unfortunately I still get the crashes disabling this. Did you have any ideas the the about:config setting?

**Comment by gildas-lormeau** [comment]
I confirm that I don't know how to circumvent this issue with `about:config`, unfortunately. BTW, if it's a regression in Waterfox, maybe you should specify it in the issue of Waterfox.

**Comment by robbely** [comment]
> BTW, if it's a regression in Waterfox, maybe you should specify it in the issue of Waterfox.

Unfortunately this is the first version of Waterfox I have tried the extension in, so cannot determine if it is a regression or just a difference in setup for Waterfox.

**Comment by robbely** [comment]
Seems fixed in G6.0.10 - I'll close this when I get confirmation here.
